const crypto=require("crypto");
function cfg(){const url=String(process.env.SUPABASE_URL||"").replace(/\/$/,""),key=String(process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY||""),secret=String(process.env.STACK_ZERO_SESSION_SECRET||key);return {url,key,secret,ok:Boolean(url&&key&&secret)}}
function b64url(buf){return Buffer.from(buf).toString("base64").replace(/=/g,"").replace(/\+/g,"-").replace(/\//g,"_")}
function hashPin(pin){const {secret}=cfg();return crypto.createHash("sha256").update(`${String(pin)}|${secret}`).digest("hex")}
function issueToken(pinHash){const {secret}=cfg(),exp=Date.now()+1000*60*60*24*180,payload=`${pinHash}.${exp}`,sig=b64url(crypto.createHmac("sha256",secret).update(payload).digest());return `${payload}.${sig}`}
function verifyToken(token){const {secret}=cfg(),parts=String(token||"").split(".");if(parts.length!==3)return null;const [pinHash,expRaw,sig]=parts,exp=Number(expRaw);if(!/^[a-f0-9]{64}$/.test(pinHash)||!Number.isFinite(exp)||exp<Date.now())return null;const payload=`${pinHash}.${expRaw}`,expected=b64url(crypto.createHmac("sha256",secret).update(payload).digest());const a=Buffer.from(sig),b=Buffer.from(expected);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return null;return {pinHash,exp}}
function authHeaders(extra={}){const {key}=cfg(),h={apikey:key,"Content-Type":"application/json",...extra};if(!key.startsWith("sb_secret_"))h.Authorization=`Bearer ${key}`;return h}
async function sb(path,opts={}){const {url,ok}=cfg();if(!ok){const e=new Error("PIN sync backend is not configured");e.status=503;throw e}const r=await fetch(url+path,{...opts,headers:authHeaders(opts.headers||{})});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok){const e=new Error(data?.message||data?.hint||data?.error||`Supabase HTTP ${r.status}`);e.status=r.status;e.data=data;throw e}return {status:r.status,data,headers:r.headers}}
async function getAccount(pinHash){const q=encodeURIComponent(pinHash),r=await sb(`/rest/v1/stack_zero_accounts?pin_hash=eq.${q}&select=pin_hash,data,updated_at&limit=1`);return Array.isArray(r.data)?r.data[0]||null:null}
module.exports={cfg,hashPin,issueToken,verifyToken,sb,getAccount};
