const PRIMARY_TTS_MODEL=process.env.GEMINI_TTS_MODEL||"gemini-3.1-flash-tts-preview";
const FALLBACK_TTS_MODEL=process.env.GEMINI_TTS_FALLBACK_MODEL||"gemini-2.5-flash-preview-tts";
const TTS_VOICE=process.env.GEMINI_TTS_VOICE||"Sulafat";
const API_BASE="https://generativelanguage.googleapis.com/v1beta/models/";
function normalizeMood(v){const m=String(v||"").toLowerCase();return ["angry","sulk","question","cry","normal","happy","flustered","smug","surprised","worried","gentle"].includes(m)?m:"normal"}
function parseRetryAfterMs(value,message=""){const raw=String(value||"").trim();if(raw){const n=Number(raw);if(Number.isFinite(n)&&n>=0)return Math.round(n*1000);const when=Date.parse(raw);if(Number.isFinite(when))return Math.max(0,when-Date.now())}const m=String(message||"").match(/retry(?:\s+in|\s+after)?\s+([0-9.]+)\s*(ms|milliseconds?|s|sec(?:onds?)?|m|min(?:utes?)?)/i);if(m){const n=Number(m[1]);if(Number.isFinite(n)){const u=m[2].toLowerCase();return Math.round(n*(u.startsWith("m")&&!u.startsWith("ms")?60000:u.startsWith("s")?1000:1))}}return 0}
function buildPrompt(text,mood,voiceStyle=""){const moodMap={angry:"controlled irritation, elegant and sharp but never shouting",sulk:"slightly sulky, restrained and soft",question:"genuine intelligent curiosity with a light questioning lift",cry:"emotionally shaken but trying to stay composed",happy:"genuinely delighted, smile audible, then composed recovery",flustered:"briefly embarrassed, tiny caught breath, soft recovery",smug:"playfully confident with restrained teasing",surprised:"one natural surprise lift, then quick recovery",worried:"quiet concern, careful and warm",gentle:"soft, warm and reassuring",normal:"calm, refined and conversational"};return `Speak only the Japanese transcript below. Do not translate, explain, or add words. Use natural contemporary Japanese pronunciation and a young-adult feminine presentation: poised, intelligent, warm, clear, slightly light in pitch, and a touch quicker than neutral conversation. Never sound childish, squeaky, shrill, like an announcer, or like AI narration. Emotion: ${moodMap[normalizeMood(mood)]||moodMap.normal}. ${String(voiceStyle||"").trim()}
Transcript: ${String(text||"").trim().slice(0,700)}`}

async function generate(model,text,mood,voiceStyle,key){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(`${API_BASE}${encodeURIComponent(model)}:generateContent`,{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":key},signal:controller.signal,body:JSON.stringify({contents:[{parts:[{text:buildPrompt(text,mood,voiceStyle)}]}],generationConfig:{responseModalities:["AUDIO"],speechConfig:{voiceConfig:{prebuiltVoiceConfig:{voiceName:TTS_VOICE}}}}})});const data=await r.json().catch(()=>({}));if(!r.ok){const msg=data?.error?.message||`Gemini TTS HTTP ${r.status}`,e=new Error(msg);e.status=r.status;e.code=data?.error?.status||"GEMINI_TTS_ERROR";e.details=data?.error||data;e.retryAfterMs=parseRetryAfterMs(r.headers?.get?.("retry-after"),msg);throw e}const part=(data?.candidates?.[0]?.content?.parts||[]).find(p=>p?.inlineData?.data),audio=part?.inlineData?.data;if(!audio){const e=new Error("Gemini TTS returned no audio");e.status=502;e.code="NO_AUDIO";throw e}const mime=String(part?.inlineData?.mimeType||part?.inlineData?.mime_type||"audio/L16;rate=24000"),sampleRate=Number((mime.match(/rate=(\d+)/i)||[])[1]||24000);return {audioBase64:audio,sampleRate,mimeType:mime,model,voice:TTS_VOICE,provider:"gemini-tts"}}catch(err){if(err?.name==="AbortError"){const e=new Error(`Gemini TTS timeout (${model})`);e.status=504;e.code="TIMEOUT";throw e}throw err}finally{clearTimeout(timer)}}
module.exports=async function handler(req,res){res.setHeader("Cache-Control","no-store");if(req.method==="OPTIONS")return res.status(204).end();if(req.method!=="POST")return res.status(405).json({ok:false,error:"Method not allowed",build:"40.8",platform:"vercel"});const key=process.env.GEMINI_API_KEY;if(!key)return res.status(500).json({ok:false,error:"GEMINI_API_KEY is not configured",code:"GEMINI_KEY_MISSING",build:"40.8",platform:"vercel"});try{const body=typeof req.body==="string"?JSON.parse(req.body||"{}"):req.body||{},text=String(body.text||"").trim().slice(0,500);if(!text)return res.status(400).json({ok:false,error:"text is required",build:"40.8",platform:"vercel"});const models=[PRIMARY_TTS_MODEL,FALLBACK_TTS_MODEL].filter((v,i,a)=>v&&a.indexOf(v)===i),attempts=[];for(const model of models){try{const out=await generate(model,text,body.mood,body.voiceStyle,key);return res.status(200).json({ok:true,build:"40.8",platform:"vercel",...out})}catch(e){attempts.push({model,status:Number(e?.status||0)||null,code:e?.code||null,message:String(e?.message||e).slice(0,240),retryAfterMs:Number(e?.retryAfterMs||0)||0});const st=Number(e?.status||0),canFallback=st===404||st===408||st===429||st>=500||e?.code==="TIMEOUT"||e?.code==="NO_AUDIO";if(!canFallback)break}}const last=attempts[attempts.length-1]||{},e=new Error(last.message||"Gemini TTS failed");e.status=last.status||502;e.code=last.code||"GEMINI_TTS_FAILED";e.retryAfterMs=Math.max(...attempts.map(x=>Number(x.retryAfterMs||0)),0);e.details={attempts};throw e}catch(err){const status=err?.status&&err.status>=400&&err.status<600?err.status:502;return res.status(status).json({ok:false,provider:"gemini-tts",error:err?.message||String(err),code:err?.code||null,retryAfterMs:Number(err?.retryAfterMs||0)||0,details:err?.details||undefined,build:"40.8",platform:"vercel"})}};
