const TTS_PROVIDER="elevenlabs";
const TTS_MODEL=process.env.ELEVENLABS_MODEL_ID||"eleven_flash_v2_5";
const TTS_VOICE_ID=process.env.ELEVENLABS_VOICE_ID||"";
const TTS_OUTPUT_FORMAT=process.env.ELEVENLABS_OUTPUT_FORMAT||"mp3_44100_128";
const ELEVENLABS_API_BASE="https://api.elevenlabs.io/v1";
function normalizeMood(v){const m=String(v||"").toLowerCase();return ["angry","sulk","question","cry","normal","happy","flustered","smug","surprised","worried","gentle"].includes(m)?m:"normal"}
function parseRetryAfterMs(value,message=""){const raw=String(value||"").trim();if(raw){const n=Number(raw);if(Number.isFinite(n)&&n>=0)return Math.round(n*1000);const when=Date.parse(raw);if(Number.isFinite(when))return Math.max(0,when-Date.now())}const m=String(message||"").match(/retry(?:\s+in|\s+after)?\s+([0-9.]+)\s*(ms|milliseconds?|s|sec(?:onds?)?|m|min(?:utes?)?)/i);if(m){const n=Number(m[1]);if(Number.isFinite(n)){const u=m[2].toLowerCase();return Math.round(n*(u.startsWith("m")&&!u.startsWith("ms")?60000:u.startsWith("s")?1000:1))}}return 0}
function elevenLabsVoiceSettings(mood,voiceStyle=""){const m=normalizeMood(mood),style=String(voiceStyle||"").toLowerCase();let stability=.42,similarity_boost=.78,styleValue=.22,speed=1.0;if(["happy","flustered","surprised"].includes(m)){stability=.30;styleValue=.38;speed=1.025}else if(m==="smug"){stability=.34;styleValue=.34;speed=.99}else if(m==="gentle"){stability=.52;styleValue=.18;speed=.975}else if(m==="worried"||m==="cry"){stability=.56;styleValue=.16;speed=.955}else if(m==="angry"){stability=.48;styleValue=.30;speed=1.0}else if(m==="sulk"){stability=.46;styleValue=.25;speed=.975}else if(m==="question"){stability=.38;styleValue=.27;speed=1.01}if(/very warm today|high trust|very close|deeply trusted/.test(style)){stability=Math.max(.25,stability-.07);styleValue=Math.min(.48,styleValue+.08);speed=Math.min(1.04,speed+.012)}else if(/warm today|clear fondness|growing closeness/.test(style)){stability=Math.max(.28,stability-.035);styleValue=Math.min(.42,styleValue+.045)}return {stability,similarity_boost,style:styleValue,use_speaker_boost:true,speed}}
function elevenLabsRequestBody(text,mood,voiceStyle=""){const body={text:String(text||"").trim().slice(0,500),model_id:TTS_MODEL,voice_settings:elevenLabsVoiceSettings(mood,voiceStyle),apply_text_normalization:"auto"};if(TTS_MODEL!=="eleven_multilingual_v2")body.language_code="ja";return body}
async function openTTSStream(text,mood,voiceStyle=""){const key=process.env.ELEVENLABS_API_KEY;if(!key){const e=new Error("ELEVENLABS_API_KEY is not configured");e.status=500;e.code="TTS_NOT_CONFIGURED";throw e}if(!TTS_VOICE_ID){const e=new Error("ELEVENLABS_VOICE_ID is not configured");e.status=500;e.code="TTS_VOICE_NOT_CONFIGURED";throw e}const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),16000);try{const url=`${ELEVENLABS_API_BASE}/text-to-speech/${encodeURIComponent(TTS_VOICE_ID)}/stream?output_format=${encodeURIComponent(TTS_OUTPUT_FORMAT)}`;const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json","Accept":"audio/mpeg","xi-api-key":key},signal:controller.signal,body:JSON.stringify(elevenLabsRequestBody(text,mood,voiceStyle))});if(!r.ok){const raw=await r.text().catch(()=>"");let details={};try{details=JSON.parse(raw)}catch(_){details={raw:raw.slice(0,500)}}const message=details?.detail?.message||details?.detail||details?.message||`ElevenLabs TTS HTTP ${r.status}`;const e=new Error(typeof message==="string"?message:JSON.stringify(message));e.status=r.status;e.code=details?.detail?.status||details?.code||"ELEVENLABS_TTS_ERROR";e.details=details;e.retryAfterMs=parseRetryAfterMs(r.headers?.get?.("retry-after"),e.message);throw e}return r}catch(err){if(err?.name==="AbortError"){const e=new Error("ElevenLabs TTS timeout");e.status=504;e.code="TIMEOUT";throw e}throw err}finally{clearTimeout(timer)}}
module.exports=async function handler(req,res){res.setHeader("Cache-Control","no-store");if(req.method==="OPTIONS")return res.status(204).end();if(req.method!=="POST")return res.status(405).json({ok:false,error:"Method not allowed",build:"40.0",platform:"vercel"});try{const body=typeof req.body==="string"?JSON.parse(req.body||"{}"):req.body||{},text=String(body.text||"").trim().slice(0,500);if(!text)return res.status(400).json({ok:false,error:"text is required",build:"40.0",platform:"vercel"});const upstream=await openTTSStream(text,body.mood,body.voiceStyle);res.status(200);res.setHeader("Content-Type",upstream.headers.get("content-type")||"audio/mpeg");res.setHeader("X-TTS-Provider",TTS_PROVIDER);res.setHeader("X-TTS-Model",TTS_MODEL);res.setHeader("X-Stack-Zero-Build","40.0");const reader=upstream.body.getReader();while(true){const {done,value}=await reader.read();if(done)break;res.write(Buffer.from(value))}return res.end()}catch(err){if(!res.headersSent)return res.status(err?.status&&err.status>=400&&err.status<600?err.status:502).json({ok:false,provider:TTS_PROVIDER,error:err?.message||"TTS stream failed",code:err?.code||null,retryAfterMs:Number(err?.retryAfterMs||0)||0,build:"40.0",platform:"vercel"});return res.end()}};
